
### CRUD BOOKS
GET http://localhost:4000/api/books/

GET http://localhost:4000/api/books/6074d5f77df0c10718c07802

POST http://localhost:4000/api/books/
content-type: application/json

{
  "read": false,
  "title": "TEST 4",
  "genre": "Historical Fiction",
  "author": "Lev Nikolayevich Tolstoy"
}

PUT http://localhost:4000/api/books/6074d5f77df0c10718c07802
content-type: application/json

{
  "read": false,
  "title": "TEST 3.3",
  "genre": "Historical Fiction put 3.4",
  "author": "Lev Nikolayevich Tolstoy 3.4"
}
### END CRUD
